# QMK enabled
LTO_ENABLE = yes

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
NKRO_ENABLE = yesw
AUDIO_ENABLE = yes
EXTRAKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes

DEFERRED_EXEC_ENABLE = yes
# QMK disabled
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
MOUSEKEY_ENABLE = no
BOOTMAGIC_ENABLE = no
BLUETOOTH_ENABLE = no
MAGIC_ENABLE = no
GRAVE_ESC_ENABLE = no
SPACE_CADET_ENABLE = no
MUSIC_ENABLE = no
