# QMK enabled
LTO_ENABLE = yes

RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = ws2812
NKRO_ENABLE = yes
AUDIO_ENABLE = yes
EXTRAKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = yes

DEFERRED_EXEC_ENABLE = yes
# QMK disabled
RGB_MATRIX_ENABLE = no
BACKLIGHT_ENABLE = no
BOOTMAGIC_ENABLE = no
BLUETOOTH_ENABLE = no
MAGIC_ENABLE = no
GRAVE_ESC_ENABLE = no
SPACE_CADET_ENABLE = no
MUSIC_ENABLE = no
